Fix building with GCC-16
CPP/7zip/Common/FileStreams.h requires additional code from 7zip. Otherwise, compilation will fail with "undefined reference to `vtable for COutFileStream'" and
"undefined reference to `NC::NFile::NIO::CFileBase::Close()'" errors.